name: Build and Commit Test

on:
  push:
    branches:
      - main

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build project
        run: |
          # Insert build commands here
          # For example:
          npm install
          npm run build
      
      - name: Commit build output
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Add build output'
          add: '.'
          default_author: github_actor
